"""...

Revision ID: 737c1e6bfc11
Revises: 20260310_0001
Create Date: 2026-10-10 00:43:21.537768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '737c1e6bfc11'
down_revision: Union[str, Sequence[str], None] = '20260310_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_messages', 'conversation_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.create_foreign_key(None, 'conversation_messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tool_approvals', 'tool_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_index(op.f('ix_tool_approvals_batch_id'), table_name='tool_approvals')
    op.drop_column('tool_approvals', 'agent_name')
    op.drop_column('tool_approvals', 'message_history')
    op.drop_column('tool_approvals', 'batch_id')
    op.drop_column('tool_approvals', 'tool_call_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_approvals', sa.Column('tool_call_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('tool_approvals', sa.Column('batch_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('tool_approvals', sa.Column('message_history', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.add_column('tool_approvals', sa.Column('agent_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_tool_approvals_batch_id'), 'tool_approvals', ['batch_id'], unique=False)
    op.alter_column('tool_approvals', 'tool_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'conversation_messages', type_='foreignkey')
    op.alter_column('conversation_messages', 'conversation_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
